// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonTasks.Domain.Data;

#nullable disable

namespace PersonTasks.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220129125621_ChangeColumnIsSolved")]
    partial class ChangeColumnIsSolved
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PersonTasks.Domain.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Todoid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Todoid");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("PersonTasks.Domain.Models.PersonTodos", b =>
                {
                    b.Property<int>("TodoId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("TodoId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("person_todos", (string)null);
                });

            modelBuilder.Entity("PersonTasks.Domain.Models.Todo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)-1);

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Todos", (string)null);
                });

            modelBuilder.Entity("PersonTasks.Domain.Models.Person", b =>
                {
                    b.HasOne("PersonTasks.Domain.Models.Todo", null)
                        .WithMany("person")
                        .HasForeignKey("Todoid");
                });

            modelBuilder.Entity("PersonTasks.Domain.Models.PersonTodos", b =>
                {
                    b.HasOne("PersonTasks.Domain.Models.Person", "person")
                        .WithMany("todos")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonTasks.Domain.Models.Todo", "todo")
                        .WithMany()
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");

                    b.Navigation("todo");
                });

            modelBuilder.Entity("PersonTasks.Domain.Models.Person", b =>
                {
                    b.Navigation("todos");
                });

            modelBuilder.Entity("PersonTasks.Domain.Models.Todo", b =>
                {
                    b.Navigation("person");
                });
#pragma warning restore 612, 618
        }
    }
}
